// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.Infrastructure.Persistence.Data;

#nullable disable

namespace Parking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Parking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParkingSpotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId")
                        .HasDatabaseName("IX_Bookings_ParkingSpotId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Bookings_UserId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("Parking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ParkingBooking.Domain.Entities.ParkingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableSpotsCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSpots")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkingLots", (string)null);
                });

            modelBuilder.Entity("ParkingBooking.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentBookingId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParkingLotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReservedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId", "Status")
                        .HasDatabaseName("IX_ParkingSpots_LotId_Status");

                    b.ToTable("ParkingSpots", (string)null);
                });

            modelBuilder.Entity("Parking.Domain.Entities.Booking", b =>
                {
                    b.OwnsOne("ParkingBooking.Domain.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPriceCurrency");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("ParkingBooking.Domain.ValueObjects.BookingPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndTime");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartTime");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Parking.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Parking.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingBooking.Domain.Entities.ParkingLot", b =>
                {
                    b.OwnsOne("ParkingBooking.Domain.ValueObjects.Money", "HourlyRate", b1 =>
                        {
                            b1.Property<Guid>("ParkingLotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("HourlyRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("HourlyRateCurrency");

                            b1.HasKey("ParkingLotId");

                            b1.ToTable("ParkingLots");

                            b1.WithOwner()
                                .HasForeignKey("ParkingLotId");
                        });

                    b.OwnsOne("ParkingBooking.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("ParkingLotId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Longitude");

                            b1.HasKey("ParkingLotId");

                            b1.ToTable("ParkingLots");

                            b1.WithOwner()
                                .HasForeignKey("ParkingLotId");
                        });

                    b.Navigation("HourlyRate")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingBooking.Domain.Entities.ParkingSpot", b =>
                {
                    b.HasOne("ParkingBooking.Domain.Entities.ParkingLot", "ParkingLot")
                        .WithMany("Spots")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ParkingBooking.Domain.ValueObjects.Money", "HourlyRate", b1 =>
                        {
                            b1.Property<Guid>("ParkingSpotId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("HourlyRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("HourlyRateCurrency");

                            b1.HasKey("ParkingSpotId");

                            b1.ToTable("ParkingSpots");

                            b1.WithOwner()
                                .HasForeignKey("ParkingSpotId");
                        });

                    b.OwnsOne("ParkingBooking.Domain.ValueObjects.SpotType", "Type", b1 =>
                        {
                            b1.Property<Guid>("ParkingSpotId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasElectricCharger")
                                .HasColumnType("INTEGER")
                                .HasColumnName("HasElectricCharger");

                            b1.Property<bool>("IsAccessible")
                                .HasColumnType("INTEGER")
                                .HasColumnName("IsAccessible");

                            b1.Property<bool>("IsCovered")
                                .HasColumnType("INTEGER")
                                .HasColumnName("IsCovered");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SpotSize");

                            b1.HasKey("ParkingSpotId");

                            b1.ToTable("ParkingSpots");

                            b1.WithOwner()
                                .HasForeignKey("ParkingSpotId");
                        });

                    b.Navigation("HourlyRate")
                        .IsRequired();

                    b.Navigation("ParkingLot");

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingBooking.Domain.Entities.ParkingLot", b =>
                {
                    b.Navigation("Spots");
                });
#pragma warning restore 612, 618
        }
    }
}
